from django.contrib.auth.decorators import login_required
from django.urls import path

from core.diary.views import (
    AddDiaryItemView,
    AddDiaryView,
    DiaryDeleteView,
    DiaryItemDeleteView,
    DiaryRestoreView,
    PlantArchiveView,
    PlantDeleteView,
    PlantingView,
    PlantMoveView,
    PlantRestoreView,
    ProfileDiaryDetailView,
    ProfileDiaryListView,
    ProfilePlantListView,
    QuickWateringView,
    UpdateDiaryItemView,
    UpdateProfileDiaryView,
)

urlpatterns = [
    path(
        "profile/plants",
        login_required(ProfilePlantListView.as_view()),
        name="profile-plant-list",
    ),
    path(
        "profile/diary/item/add/<int:diary_id>",
        login_required(AddDiaryItemView.as_view()),
        name="profile-diary-item-add",
    ),
    path(
        "profile/diary/item/<int:pk>/delete/",
        login_required(DiaryItemDeleteView.as_view()),
        name="profile-diary-item-delete",
    ),
    path(
        "profile/diary/item/<int:pk>/update/",
        login_required(UpdateDiaryItemView.as_view()),
        name="profile-diary-item-update",
    ),
    path(
        "profile/diary/<int:diary_id>/plant/add/",
        login_required(PlantingView.as_view()),
        name="profile-diary-plant-add",
    ),
    path(
        "profile/diary/<int:diary_pk>/plant/<int:plant_pk>/archive/",
        login_required(PlantArchiveView.as_view()),
        name="profile-diary-plant-archive",
    ),
    path(
        "profile/diary/<int:diary_pk>/plant/<int:plant_pk>/restore/",
        login_required(PlantRestoreView.as_view()),
        name="profile-diary-plant-restore",
    ),
    path(
        "profile/diary/<int:diary_pk>/plant/<int:plant_pk>/delete/",
        login_required(PlantDeleteView.as_view()),
        name="profile-diary-plant-delete",
    ),
    path(
        "profile/diary/<int:pk>",
        login_required(ProfileDiaryDetailView.as_view()),
        name="profile-diary-detail",
    ),
    path(
        "profile/diary/<int:pk>/delete/",
        login_required(DiaryDeleteView.as_view()),
        name="profile-diary-delete",
    ),
    path(
        "profile/diary/<int:pk>/restore/",
        login_required(DiaryRestoreView.as_view()),
        name="profile-diary-restore",
    ),
    path(
        "profile/diary/<int:pk>/quick-watering/",
        login_required(QuickWateringView.as_view()),
        name="profile-diary-quick-watering",
    ),
    path(
        "profile/diary/<int:diary_pk>/plant/<int:plant_pk>/move/",
        login_required(PlantMoveView.as_view()),
        name="profile-diary-plant-move",
    ),
    path(
        "profile/diary/update/<int:pk>",
        login_required(UpdateProfileDiaryView.as_view()),
        name="profile-diary-update",
    ),
    path("profile/diary/add", login_required(AddDiaryView.as_view()), name="profile-diary-add"),
    path("profile/diary", login_required(ProfileDiaryListView.as_view()), name="profile-diary-list"),
]
