# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 11:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='comment text')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment date')),
            ],
            options={
                'db_table': 'comment',
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='image')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='photo describing')),
                ('description_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='photo describing')),
                ('description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='photo describing')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='author of photo')),
                ('author_uk', models.CharField(blank=True, max_length=150, null=True, verbose_name='author of photo')),
                ('author_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='author of photo')),
                ('source', models.CharField(blank=True, max_length=150, null=True, verbose_name='photo source')),
                ('source_uk', models.CharField(blank=True, max_length=150, null=True, verbose_name='photo source')),
                ('source_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='photo source')),
            ],
            options={
                'db_table': 'photo',
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='post title')),
                ('title_uk', models.CharField(max_length=500, null=True, verbose_name='post title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='post title')),
                ('text', ckeditor.fields.RichTextField(verbose_name='post text')),
                ('text_uk', ckeditor.fields.RichTextField(null=True, verbose_name='post text')),
                ('text_en', ckeditor.fields.RichTextField(null=True, verbose_name='post text')),
                ('slug', models.CharField(max_length=250, unique=True, verbose_name='transliteration value')),
                ('work_status', models.IntegerField(blank=True, choices=[(1, 'Translate'), (2, 'Publish')], default=None, null=True, verbose_name='status of author work')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='post author')),
                ('author_uk', models.CharField(blank=True, max_length=250, null=True, verbose_name='post author')),
                ('author_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='post author')),
                ('source', models.CharField(blank=True, max_length=250, null=True, verbose_name='post source')),
                ('source_uk', models.CharField(blank=True, max_length=250, null=True, verbose_name='post source')),
                ('source_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='post source')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of publish')),
                ('hits', models.IntegerField(default=0, verbose_name='count of views')),
                ('status', models.BooleanField(default=1, verbose_name='post status')),
            ],
            options={
                'db_table': 'post',
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
