# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_field', models.CharField(max_length=20, verbose_name='region')),
            ],
            options={
                'db_table': 'region',
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=b'uploads/avatars/', verbose_name='avatar')),
                ('phone', models.IntegerField(blank=True, unique=True, verbose_name='phone')),
                ('birth_date', models.DateField(blank=True, verbose_name='birth date')),
                ('about', models.TextField(blank=True, verbose_name='about you')),
                ('breed', models.TextField(blank=True, verbose_name='pigeons breed')),
                ('location', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='uagent.Region', verbose_name='location')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_information',
                'verbose_name': 'user information',
                'verbose_name_plural': 'user information',
            },
        ),
    ]
