# Generated by Django 3.1.6 on 2021-03-02 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210302_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='date',
        ),
        migrations.AddField(
            model_name='diaryitem',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
