# Generated by Django 4.2.1 on 2023-05-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210302_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryitem',
            options={'ordering': ('-date',)},
        ),
    ]
