# Generated by Django 5.0.3 on 2025-01-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0004_alter_diaryitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Хочу щоб бачили всі"),
        ),
        migrations.AlterField(
            model_name="diaryitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="diaries/images", verbose_name="Фото"),
        ),
    ]
