# Generated by Django 5.0.3 on 2026-04-14 12:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0005_alter_diary_public_alter_diaryitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="plant_date",
            field=models.DateField(default=datetime.date.today, verbose_name="Дата"),
        ),
    ]
