# Generated by Django 5.0.3 on 2026-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0006_diary_plant_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="plant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tomatoes", "Помідор"),
                    ("cucumbers", "Огірок"),
                    ("sweet_pepper", "Перець солодкий"),
                    ("hot_pepper", "Перець гострий"),
                    ("zucchini", "Кабачок"),
                    ("eggplant", "Баклажан"),
                    ("lettuce", "Салат"),
                    ("radish", "Редиска"),
                    ("basil", "Базилік"),
                    ("parsley", "Петрушка"),
                    ("strawberry", "Полуниця"),
                    ("raspberry", "Малина"),
                    ("blueberry", "Чорниця"),
                    ("wild_strawberry", "Суниця"),
                    ("dill", "Кріп"),
                    ("green_onion", "Зелена цибуля"),
                    ("mint", "М'ята"),
                    ("arugula", "Рукола"),
                    ("spinach", "Шпинат"),
                ],
                default="",
                max_length=50,
                verbose_name="Вид рослини",
            ),
        ),
    ]
