# Generated by Django 5.0.3 on 2026-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0007_diary_plant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryitem",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("watering", "💧 Підлив"),
                    ("fertilizer", "🌿 Добриво"),
                    ("photo", "📷 Фото"),
                    ("note", "✏️ Нотатка"),
                    ("planted", "🌱 Посаджено"),
                    ("disease", "🤒 Хвороба"),
                    ("pest", "🐛 Шкідник"),
                    ("pruning", "✂️ Обрізка"),
                    ("harvest", "🧺 Збір урожаю"),
                ],
                default="",
                max_length=32,
                verbose_name="Оберіть швидку дію",
            ),
        ),
    ]
