# Generated by Django 5.0.3 on 2026-04-17 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0008_diaryitem_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryitem",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Опис"),
        ),
    ]
