# Generated by Django 5.0.3 on 2026-04-26

from datetime import date

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0011_category_absolute_url"),
        ("diary", "0009_alter_diaryitem_description"),
        ("pro_auth", "0006_auto_20180416_1655"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Архівований"),
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Назва")),
                ("variety", models.CharField(blank=True, max_length=255, verbose_name="Сорт")),
                ("description", ckeditor.fields.RichTextField(blank=True, verbose_name="Опис")),
                ("plant_date", models.DateField(default=date.today, verbose_name="Дата посадки")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("completed", "Завершена")],
                        default="active",
                        max_length=16,
                        verbose_name="Статус рослини",
                    ),
                ),
                ("completed_at", models.DateField(blank=True, null=True, verbose_name="Дата завершення")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="plants",
                        to="classifier.category",
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="plants",
                        to="pro_auth.user",
                    ),
                ),
            ],
            options={
                "ordering": ("created", "id"),
            },
        ),
        migrations.AddField(
            model_name="diary",
            name="plants",
            field=models.ManyToManyField(
                blank=True,
                related_name="diaries",
                to="diary.plant",
                verbose_name="Рослини",
            ),
        ),
        migrations.AddField(
            model_name="diaryitem",
            name="apply_to_all",
            field=models.BooleanField(
                default=True,
                verbose_name="Застосувати до всіх активних рослин",
            ),
        ),
        migrations.AddField(
            model_name="diaryitem",
            name="plants",
            field=models.ManyToManyField(
                blank=True,
                related_name="diary_items",
                to="diary.plant",
                verbose_name="Рослини",
            ),
        ),
    ]
