# Generated by Django 5.0.3 on 2026-04-24 12:00

from datetime import date

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0009_alter_diaryitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Архівований"),
        ),
        migrations.CreateModel(
            name="DiaryPlant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Сорт рослини")),
                (
                    "plant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tomatoes", "Помідор"),
                            ("cucumbers", "Огірок"),
                            ("sweet_pepper", "Перець солодкий"),
                            ("hot_pepper", "Перець гострий"),
                            ("zucchini", "Кабачки (цукіні)"),
                            ("eggplant", "Баклажани"),
                            ("lettuce", "Салат"),
                            ("carrot", "Морква"),
                            ("radish", "Редиска"),
                            ("basil", "Базилік"),
                            ("parsley", "Петрушка"),
                            ("strawberry", "Полуниця"),
                            ("raspberry", "Малина"),
                            ("blueberry", "Чорниця"),
                            ("wild_strawberry", "Суниця"),
                            ("dill", "Кріп"),
                            ("green_onion", "Зелена цибуля"),
                            ("mint", "М'ята"),
                            ("arugula", "Рукола"),
                            ("spinach", "Шпинат"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Вид рослини",
                    ),
                ),
                ("plant_date", models.DateField(default=date.today, verbose_name="Дата посадки")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("completed", "Завершена")],
                        default="active",
                        max_length=16,
                        verbose_name="Статус рослини",
                    ),
                ),
                ("completed_at", models.DateField(blank=True, null=True, verbose_name="Дата завершення")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "diary",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="plants", to="diary.diary"),
                ),
            ],
            options={
                "ordering": ("created", "id"),
            },
        ),
        migrations.AddField(
            model_name="diaryitem",
            name="apply_to_all",
            field=models.BooleanField(default=True, verbose_name="Застосувати до всіх активних рослин"),
        ),
        migrations.AddField(
            model_name="diaryitem",
            name="plants",
            field=models.ManyToManyField(blank=True, related_name="diary_items", to="diary.diaryplant", verbose_name="Рослини"),
        ),
    ]
