# Generated by Django 5.0.3 on 2026-04-26 11:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0010_plant_diary_plants_and_item_targets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Короткий опис"),
        ),
    ]
