# Generated by Django 5.0.3 on 2026-04-24 12:20

from django.db import migrations


def migrate_existing_diaries_to_diaryplant(apps, schema_editor):
    Diary = apps.get_model("diary", "Diary")
    DiaryPlant = apps.get_model("diary", "DiaryPlant")
    DiaryItem = apps.get_model("diary", "DiaryItem")

    for diary in Diary.objects.all().iterator():
        plant = DiaryPlant.objects.filter(diary_id=diary.id).order_by("id").first()
        if plant is None:
            plant = DiaryPlant.objects.create(
                diary_id=diary.id,
                title=diary.title,
                plant_type=diary.plant_type,
                plant_date=diary.plant_date,
                status="active",
            )

        for diary_item in DiaryItem.objects.filter(diary_id=diary.id).iterator():
            diary_item.apply_to_all = False
            diary_item.save(update_fields=["apply_to_all"])
            diary_item.plants.add(plant)


def reverse_migrate_existing_diaries_to_diaryplant(apps, schema_editor):
    Diary = apps.get_model("diary", "Diary")
    DiaryPlant = apps.get_model("diary", "DiaryPlant")
    DiaryItem = apps.get_model("diary", "DiaryItem")

    for diary in Diary.objects.all().iterator():
        plants = list(DiaryPlant.objects.filter(diary_id=diary.id).order_by("id"))
        if len(plants) != 1:
            continue

        plant = plants[0]
        matches_legacy_diary = (
            plant.title == diary.title
            and plant.plant_type == diary.plant_type
            and plant.plant_date == diary.plant_date
            and plant.status == "active"
            and plant.completed_at is None
        )
        if not matches_legacy_diary:
            continue

        diary_items = DiaryItem.objects.filter(diary_id=diary.id)
        if diary_items.exclude(plants=plant).exists():
            continue

        for diary_item in diary_items.iterator():
            diary_item.plants.remove(plant)
            diary_item.apply_to_all = True
            diary_item.save(update_fields=["apply_to_all"])

        plant.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0010_diaryplant_diary_is_archived_diaryitem_targets"),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_diaries_to_diaryplant,
            reverse_migrate_existing_diaries_to_diaryplant,
        ),
    ]
