# Generated by Django 5.0.3 on 2026-04-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0011_alter_diary_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diaryitem",
            name="apply_to_all",
        ),
    ]
