# Generated by Django 5.0.3 on 2026-04-26

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0012_remove_diaryitem_apply_to_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="updated",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="diaryitem",
            options={"ordering": ("-date", "-created")},
        ),
    ]
