# Generated by Django 5.0.3 on 2026-04-30

from django.db import migrations, models


def set_existing_diary_items_apply_to_all_false(apps, schema_editor):
    DiaryItem = apps.get_model("diary", "DiaryItem")
    DiaryItem.objects.all().update(apply_to_all=False)


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0014_alter_diaryitem_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryitem",
            name="apply_to_all",
            field=models.BooleanField(default=True, verbose_name="Застосувати до всіх активних рослин"),
        ),
        migrations.RunPython(
            set_existing_diary_items_apply_to_all_false,
            migrations.RunPython.noop,
        ),
    ]
