# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='category')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='category slug')),
                ('level', models.IntegerField(verbose_name='level')),
                ('parent', models.CharField(default=b'root', max_length=20, verbose_name='category parent')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
