# Generated by Django 1.9.9 on 2016-10-06 16:07
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_metadata'),
        ('posts', '0004_post_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post-meta-data+', to='services.MetaData', verbose_name='post meta data'),
        ),
    ]
