# Generated by Django 2.0.3 on 2018-03-18 09:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20171008_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('is_parsed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='ParsedMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=500)),
                ('map', models.TextField()),
                ('root', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParsedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='parsed title')),
                ('original', ckeditor.fields.RichTextField(verbose_name='parsed text')),
                ('translated_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='translated title')),
                ('translated', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='translated text')),
                ('is_processed', models.BooleanField(default=False)),
                ('hash', models.CharField(max_length=500)),
            ],
        ),
    ]
