# Generated by Django 2.0.3 on 2018-11-04 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_auto_20181104_2137'),
        ('posts', '0010_auto_20180415_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.Country', verbose_name='post country'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='classifier.Tag', verbose_name='past tags'),
        ),
    ]
