# Generated by Django 2.0.8 on 2019-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190118_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255, verbose_name='fingerprint')),
                ('search_phrase', models.CharField(max_length=255, verbose_name='fingerprint')),
            ],
        ),
        migrations.CreateModel(
            name='UsefulStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255, verbose_name='fingerprint')),
                ('post_id', models.IntegerField(verbose_name='post identifier')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='user identifier')),
                ('is_useful', models.BooleanField(verbose_name='is useful post')),
            ],
        ),
    ]
