# Generated by Django 2.0.8 on 2019-04-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_searchstatistic_usefulstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
