# Generated by Django 2.0.8 on 2019-04-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20190401_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author_uk',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='source_en',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='source_uk',
        ),
    ]
