# Generated by Django 2.0.13 on 2019-08-27 14:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20190401_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_search'], name='post_text_se_18be37_gin'),
        ),
    ]
