# Generated by Django 2.0.13 on 2019-08-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20190827_1444'),
    ]

    migration = '''
            CREATE TRIGGER text_search_update BEFORE INSERT OR UPDATE ON post FOR EACH ROW EXECUTE PROCEDURE 
            tsvector_update_trigger(text_search, 'pg_catalog.english', text); 
            UPDATE post set ID = ID;
        '''

    reverse_migration = '''
            DROP TRIGGER text_search_update ON post;
        '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
