# Generated by Django 2.0.13 on 2019-10-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20191019_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='absolute_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
