# Generated by Django 4.2.1 on 2023-06-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_postview_created_searchstatistic_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date of update'),
        ),
    ]
