# Generated by Django 5.0.3 on 2024-05-05 11:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0011_category_absolute_url"),
        ("posts", "0025_post_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classifier.country",
                verbose_name="origin country",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                help_text="Enter sources separated by commas",
                null=True,
                size=None,
                verbose_name="post sources",
            ),
        ),
    ]
