# Generated by Django 5.0.3 on 2024-05-26 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0026_alter_post_country_alter_post_sources"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Link",
        ),
        migrations.RemoveField(
            model_name="parsedpost",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="parsedpost",
            name="rubric",
        ),
        migrations.DeleteModel(
            name="PostView",
        ),
        migrations.DeleteModel(
            name="ParsedPost",
        ),
    ]
