# Generated by Codex on 2026-06-26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0027_delete_link_remove_parsedpost_publisher_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE post
                    ALTER COLUMN sources TYPE text
                    USING CASE
                        WHEN sources IS NULL THEN NULL
                        WHEN array_length(sources, 1) IS NULL THEN ''
                        ELSE '<ul><li>' || array_to_string(sources, '</li><li>') || '</li></ul>'
                    END;
                    """,
                    reverse_sql="""
                    ALTER TABLE post
                    ALTER COLUMN sources TYPE varchar(250)[]
                    USING CASE
                        WHEN sources IS NULL OR btrim(sources) = '' THEN NULL
                        ELSE ARRAY[
                            left(regexp_replace(sources, '<[^>]*>', '', 'g'), 250)
                        ]::varchar(250)[]
                    END;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="post",
                    name="sources",
                    field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="post sources"),
                ),
            ],
        ),
    ]
