# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0027_delete_link_remove_parsedpost_publisher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="apple_attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="apple variety attributes"),
        ),
    ]
