# Generated by Django 6.0.5 on 2026-06-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0028_alter_post_sources_rich_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="apple_attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="apple variety attributes"),
        ),
    ]
