# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


def seed_category_attribute_schemas(apps, schema_editor):
    from core.posts.apple_attributes import (
        APPLE_VARIETY_ATTRIBUTE_GROUPS,
        APPLE_VARIETY_PARENT_SLUG,
        APPLE_VARIETY_RUBRIC_SLUG,
    )

    Category = apps.get_model("classifier", "Category")
    CategoryAttributeGroup = apps.get_model("posts", "CategoryAttributeGroup")
    CategoryAttributeField = apps.get_model("posts", "CategoryAttributeField")
    CategoryAttributeChoice = apps.get_model("posts", "CategoryAttributeChoice")
    Post = apps.get_model("posts", "Post")

    for post in Post.objects.exclude(category_attributes={}).iterator():
        attributes = post.category_attributes or {}
        if attributes and not _looks_like_category_bucket(attributes):
            post.category_attributes = {str(post.rubric_id): attributes}
            post.save(update_fields=["category_attributes"])

    category = Category.objects.filter(
        slug=APPLE_VARIETY_RUBRIC_SLUG,
        parent__slug=APPLE_VARIETY_PARENT_SLUG,
    ).first()
    if not category:
        return

    for group_order, group in enumerate(APPLE_VARIETY_ATTRIBUTE_GROUPS, start=10):
        group_obj, _ = CategoryAttributeGroup.objects.update_or_create(
            category=category,
            title=group["title"],
            defaults={
                "is_active": True,
                "sort_order": group_order,
            },
        )
        for field_order, field in enumerate(group["fields"], start=10):
            field_obj, _ = CategoryAttributeField.objects.update_or_create(
                category=category,
                key=field["key"],
                defaults={
                    "group": group_obj,
                    "label": field["label"],
                    "field_type": "multiselect" if field["multiple"] else "select",
                    "is_active": True,
                    "is_filterable": True,
                    "is_public": True,
                    "sort_order": field_order,
                },
            )
            for choice_order, (value, label) in enumerate(field["choices"], start=10):
                CategoryAttributeChoice.objects.update_or_create(
                    field=field_obj,
                    value=value,
                    defaults={
                        "label": label,
                        "is_active": True,
                        "is_public": True,
                        "sort_order": choice_order,
                    },
                )


def _looks_like_category_bucket(attributes):
    return all(str(key).isdigit() and isinstance(value, dict) for key, value in attributes.items())


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0014_categoryaiprofile_recommendation_rules"),
        ("posts", "0029_post_apple_attributes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="apple_attributes",
            new_name="category_attributes",
        ),
        migrations.AlterField(
            model_name="post",
            name="category_attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="category attributes"),
        ),
        migrations.CreateModel(
            name="CategoryAttributeGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="sort order")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_groups",
                        to="classifier.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category attribute group",
                "verbose_name_plural": "Category attribute groups",
                "db_table": "category_attribute_group",
                "ordering": ("category__value", "sort_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="CategoryAttributeField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=120, verbose_name="key")),
                ("label", models.CharField(max_length=250, verbose_name="label")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("select", "select"),
                            ("multiselect", "multiple select"),
                            ("integer", "integer"),
                            ("decimal", "decimal"),
                            ("range", "range"),
                            ("boolean", "boolean"),
                        ],
                        max_length=20,
                        verbose_name="field type",
                    ),
                ),
                ("help_text", models.TextField(blank=True, verbose_name="help text")),
                ("unit", models.CharField(blank=True, max_length=50, verbose_name="unit")),
                ("decimal_places", models.PositiveSmallIntegerField(default=0, verbose_name="decimal places")),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="minimum value",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="maximum value",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("is_required", models.BooleanField(default=False, verbose_name="required")),
                ("is_filterable", models.BooleanField(default=True, verbose_name="filterable")),
                ("is_public", models.BooleanField(default=True, verbose_name="public")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="sort order")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_fields",
                        to="classifier.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fields",
                        to="posts.categoryattributegroup",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category attribute field",
                "verbose_name_plural": "Category attribute fields",
                "db_table": "category_attribute_field",
                "ordering": ("category__value", "group__sort_order", "sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="CategoryAttributeChoice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.SlugField(max_length=120, verbose_name="value")),
                ("label", models.CharField(max_length=250, verbose_name="label")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("is_public", models.BooleanField(default=True, verbose_name="public")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="sort order")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="posts.categoryattributefield",
                        verbose_name="field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category attribute choice",
                "verbose_name_plural": "Category attribute choices",
                "db_table": "category_attribute_choice",
                "ordering": ("field__sort_order", "sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="PostAttributeValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value_text", models.CharField(blank=True, max_length=250, verbose_name="text value")),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="number value",
                    ),
                ),
                (
                    "value_number_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="minimum number value",
                    ),
                ),
                (
                    "value_number_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="maximum number value",
                    ),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True, verbose_name="boolean value")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classifier.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_values",
                        to="posts.categoryattributechoice",
                        verbose_name="choice",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_values",
                        to="posts.categoryattributefield",
                        verbose_name="field",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="posts.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post attribute value",
                "verbose_name_plural": "Post attribute values",
                "db_table": "post_attribute_value",
            },
        ),
        migrations.AddConstraint(
            model_name="categoryattributefield",
            constraint=models.UniqueConstraint(
                fields=("category", "key"),
                name="unique_category_attribute_field_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryattributechoice",
            constraint=models.UniqueConstraint(
                fields=("field", "value"),
                name="unique_category_attribute_choice_value",
            ),
        ),
        migrations.AddIndex(
            model_name="postattributevalue",
            index=models.Index(fields=("category", "field"), name="post_attrib_categor_068a88_idx"),
        ),
        migrations.AddIndex(
            model_name="postattributevalue",
            index=models.Index(fields=("post", "field"), name="post_attrib_post_id_ede88d_idx"),
        ),
        migrations.AddIndex(
            model_name="postattributevalue",
            index=models.Index(fields=("field", "choice"), name="post_attrib_field_i_41c4cd_idx"),
        ),
        migrations.AddIndex(
            model_name="postattributevalue",
            index=models.Index(
                fields=("field", "value_number_min", "value_number_max"),
                name="post_attrib_field_i_a3bb9f_idx",
            ),
        ),
        migrations.RunPython(seed_category_attribute_schemas, migrations.RunPython.noop),
    ]
