# Generated by Codex on 2026-06-28

from decimal import Decimal, InvalidOperation

from django.db import migrations

DECIMAL_PARSE_ERRORS = (InvalidOperation, ValueError)


def backfill_post_attribute_values(apps, schema_editor):
    CategoryAttributeChoice = apps.get_model("posts", "CategoryAttributeChoice")
    CategoryAttributeField = apps.get_model("posts", "CategoryAttributeField")
    Post = apps.get_model("posts", "Post")
    PostAttributeValue = apps.get_model("posts", "PostAttributeValue")

    PostAttributeValue.objects.all().delete()
    for post in Post.objects.exclude(category_attributes={}).iterator():
        attributes = (post.category_attributes or {}).get(str(post.rubric_id), {})
        if not attributes:
            continue
        fields = CategoryAttributeField.objects.filter(category_id=post.rubric_id, is_active=True, is_filterable=True)
        for field in fields:
            value = attributes.get(field.key)
            if value in (None, "", [], ()):
                continue
            _create_index_values(PostAttributeValue, CategoryAttributeChoice, post, field, value)


def _create_index_values(PostAttributeValue, CategoryAttributeChoice, post, field, value):
    if field.field_type == "select":
        choice = CategoryAttributeChoice.objects.filter(field=field, value=value, is_active=True).first()
        if choice:
            PostAttributeValue.objects.create(
                post_id=post.pk,
                category_id=post.rubric_id,
                field=field,
                choice=choice,
                value_text=choice.value,
            )
        return

    if field.field_type == "multiselect":
        for item in value:
            choice = CategoryAttributeChoice.objects.filter(field=field, value=item, is_active=True).first()
            if choice:
                PostAttributeValue.objects.create(
                    post_id=post.pk,
                    category_id=post.rubric_id,
                    field=field,
                    choice=choice,
                    value_text=choice.value,
                )
        return

    if field.field_type == "boolean":
        PostAttributeValue.objects.create(
            post_id=post.pk,
            category_id=post.rubric_id,
            field=field,
            value_boolean=bool(value),
        )
        return

    if field.field_type in ("integer", "decimal"):
        number = _optional_decimal(value)
        if number is not None:
            PostAttributeValue.objects.create(
                post_id=post.pk,
                category_id=post.rubric_id,
                field=field,
                value_number=number,
            )
        return

    if field.field_type == "range" and isinstance(value, dict):
        PostAttributeValue.objects.create(
            post_id=post.pk,
            category_id=post.rubric_id,
            field=field,
            value_number_min=_optional_decimal(value.get("min")),
            value_number_max=_optional_decimal(value.get("max")),
        )


def _optional_decimal(value):
    if value in (None, ""):
        return None
    try:
        return Decimal(str(value).strip())
    except DECIMAL_PARSE_ERRORS:
        return None


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0030_category_attribute_schemas"),
    ]

    operations = [
        migrations.RunPython(backfill_post_attribute_values, migrations.RunPython.noop),
    ]
