# Generated by Codex on 2026-07-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0031_backfill_post_attribute_values"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-publish_date"],
                "permissions": [("change_own_post", "Can view and change own posts")],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
