# Generated by Django 5.0.3 on 2024-05-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0008_company_type_product_max_price_product_min_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("max_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("discount_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("UAH", "грн."), ("USD", "$"), ("EUR", "€"), ("GBP", "£")],
                        default="UAH",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prices",
                        to="companies.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
            },
        ),
    ]
