# Generated by Django 1.10.4 on 2017-05-16 14:28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170217_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='meta text'),
        ),
    ]
