# Generated by Django 1.10.4 on 2017-06-17 08:16
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_metadata_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='meta text'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='text_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='meta text'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='meta text'),
        ),
    ]
