# Generated by Django 2.0.8 on 2019-04-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170617_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='h1_en',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='h1_uk',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='text_uk',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='title_uk',
        ),
    ]
