# Generated by Django 5.0.3 on 2026-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_feedback_created_reviews_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Тема"),
        ),
    ]
