# Generated by Django 2.0.3 on 2018-03-17 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
