# Generated by Django 2.0.8 on 2019-04-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180317_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='title_uk',
        ),
    ]
