# Generated by Django 1.10.4 on 2017-01-24 10:34
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_auto_20161006_1607'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
