# Generated by Django 2.0.8 on 2019-04-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_tags'),
        ('classifier', '0005_auto_20181104_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
