# Generated by Django 2.0.8 on 2019-04-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_auto_20190401_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='area',
            name='value_uk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='value_uk',
        ),
        migrations.RemoveField(
            model_name='country',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='value_uk',
        ),
        migrations.RemoveField(
            model_name='location',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='location',
            name='value_uk',
        ),
        migrations.RemoveField(
            model_name='region',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='value_uk',
        ),
    ]
