# Generated by Django 5.0.3 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0011_category_absolute_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_diary_species_parent",
            field=models.BooleanField(default=False, verbose_name="diary species parent"),
        ),
    ]
