# Generated by Django 6.0.5 on 2026-05-29 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0012_category_is_diary_species_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAIProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional readable title, for example: Basil (Ocimum basilicum).', max_length=255, verbose_name='AI profile title')),
                ('content', models.TextField(blank=True, help_text='Structured plain text or Markdown used as private AI context. This text is not published.', verbose_name='AI knowledge content')),
                ('sources', models.TextField(blank=True, help_text='Optional links, books, notes, or source references for this knowledge profile.', verbose_name='sources')),
                ('internal_notes', models.TextField(blank=True, help_text='Optional team-only notes. Not intended for AI prompts by default.', verbose_name='internal notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_ai_enabled', models.BooleanField(default=True, verbose_name='use for AI recommendations')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='classifier.category', verbose_name='category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_category_ai_profiles', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'AI documentation',
                'verbose_name_plural': 'AI documentation',
                'db_table': 'classifier_category_ai_profile',
                'ordering': ['category__value'],
            },
        ),
    ]
