# Generated by Django 6.0.5 on 2026-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0013_categoryaiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryaiprofile',
            name='recommendation_rules',
            field=models.TextField(blank=True, help_text='Structured rules for risks, triggers, confidence, and recommendations used as private AI context.', verbose_name='AI recommendation rules'),
        ),
    ]
