# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_meta_description'),
        ('pro_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choices_owner',
            field=models.ManyToManyField(blank=True, related_name='user_post', to='posts.Post', verbose_name='relation with posts'),
        ),
        migrations.AddField(
            model_name='user',
            name='validation_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mail validation key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. You use it at every entrance to the site.', max_length=254, unique=True, verbose_name='user email'),
        ),
    ]
