# Generated by Django 2.0.3 on 2018-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_auth', '0002_auto_20160615_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='main phone'),
        ),
    ]
