# Generated by Django 2.0.3 on 2018-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_auth', '0003_auto_20180415_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. You use it at every entrance to the site.', max_length=254, null=True, unique=True, verbose_name='user email'),
        ),
    ]
