# Generated by Django 2.0.3 on 2018-04-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_auth', '0004_auto_20180415_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
