# Generated by Django 2.0.3 on 2018-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_auth', '0005_remove_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. You use it at every entrance to the site.', max_length=254, null=True, verbose_name='user email'),
        ),
    ]
