# Generated by Django 3.0.8 on 2020-12-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0010_auto_20201201_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='adverts/images', verbose_name='image')),
                ('author', models.CharField(blank=True, max_length=512, null=True)),
                ('contact', models.CharField(max_length=512)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.Category')),
            ],
        ),
    ]
