# Generated by Django 3.0.8 on 2020-12-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_auto_20201201_1933'),
        ('adverts', '0002_advert_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.Location', verbose_name='user location'),
        ),
        migrations.AddField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
