# Generated by Django 4.2.7 on 2023-11-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_advert_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['-updated'], 'verbose_name': 'advert', 'verbose_name_plural': 'adverts'},
        ),
        migrations.AddField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
