# Generated by Django 5.0.2 on 2024-03-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0009_advert_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'default_manager_name': 'objects', 'ordering': ['-updated'], 'verbose_name': 'advert', 'verbose_name_plural': 'adverts'},
        ),
    ]
