# Generated by Django 5.0.3 on 2024-05-15 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adverts", "0010_alter_advert_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="advert",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
