# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adverts", "0011_advert_views_alter_advert_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="adverts/images", verbose_name="image"),
        ),
        migrations.CreateModel(
            name="AdvertImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="adverts/images", verbose_name="image")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="adverts.advert"
                    ),
                ),
            ],
            options={
                "verbose_name": "advert photo",
                "verbose_name_plural": "advert photos",
                "ordering": ["created", "pk"],
            },
        ),
    ]
