# Generated by Django 5.0.3 on 2024-04-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_varietycategory_variety"),
    ]

    operations = [
        migrations.AddField(
            model_name="varietycategory",
            name="absolute_url",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="category absolute url"),
        ),
    ]
