# Generated by Django 5.0.3 on 2024-04-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0003_varietycategory_absolute_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="absolute_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
