# Generated by Django 2.1.15 on 2019-12-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
