# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='meta title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='meta title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='meta title')),
                ('description', models.CharField(max_length=255, verbose_name='meta description')),
                ('description_uk', models.CharField(max_length=255, null=True, verbose_name='meta description')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='meta description')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta_description')),
                ('h1_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta_description')),
                ('h1_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta_description')),
            ],
            options={
                'verbose_name': 'meta data',
                'verbose_name_plural': 'meta data',
                'db_table': 'metadata',
            },
        ),
    ]
