# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 09:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('text', models.TextField(verbose_name='text')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='post author')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Category', verbose_name='category')),
            ],
            options={
                'db_table': 'post',
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_photo_field', models.ImageField(upload_to=b'uploads/post_photos/', verbose_name='post photo')),
            ],
            options={
                'db_table': 'post_photo',
                'verbose_name': 'post photo',
                'verbose_name_plural': 'post photos',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ManyToManyField(to='posts.PostPhoto', verbose_name='post images'),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='post publisher'),
        ),
    ]
