# Generated by Django 5.0.2 on 2024-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_company_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="auction_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UAH", "Ukrainian Hryvnia"),
                    ("USD", "United States Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound Sterling"),
                ],
                default="UAH",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="auction_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
