# Generated by Django 5.0.2 on 2024-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_product_auction_currency_product_auction_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="parser_map",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
