# Generated by Django 5.0.3 on 2024-03-23 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0011_category_absolute_url"),
        ("companies", "0005_company_parser_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="classifier.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="auction_currency",
            field=models.CharField(
                blank=True,
                choices=[("UAH", "грн."), ("USD", "$"), ("EUR", "€"), ("GBP", "£")],
                default="UAH",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("UAH", "грн."), ("USD", "$"), ("EUR", "€"), ("GBP", "£")],
                default="UAH",
                null=True,
            ),
        ),
    ]
