# Generated by Django 5.0.3 on 2024-03-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0011_category_absolute_url"),
        ("companies", "0006_product_category_alter_product_auction_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField()),
                ("parser_map", models.JSONField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("last_crawled", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_crawl_status", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links", to="classifier.category"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links", to="companies.company"
                    ),
                ),
            ],
        ),
    ]
