# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_company_type_product_max_price_product_min_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="crawl_interval_minutes",
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name="link",
            name="experiment_label",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="link",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="link",
            name="last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="last_product_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="link",
            name="last_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="leased_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="leased_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="parser_config_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="link",
            name="priority",
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name="link",
            name="source_type",
            field=models.CharField(
                choices=[("static", "Static HTML"), ("browser", "Browser-rendered page")],
                default="static",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="source_product_key",
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="source_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="companies.link",
            ),
        ),
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("max_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("min_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("UAH", "грн."), ("USD", "$"), ("EUR", "€"), ("GBP", "£")],
                        default="UAH",
                        null=True,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("raw_price", models.CharField(blank=True, max_length=255)),
                ("worker_name", models.CharField(blank=True, max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="companies.product",
                    ),
                ),
                (
                    "source_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_history",
                        to="companies.link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product price history",
                "verbose_name_plural": "Product price history",
                "ordering": ["-observed_at", "-created"],
            },
        ),
        migrations.AlterModelOptions(
            name="link",
            options={"permissions": [("use_parser_worker_api", "Can use parser worker API")]},
        ),
    ]
