# Generated by Django 6.0.6 on 2026-06-28 20:06

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F, Q


def backfill_product_price_updated_at(apps, schema_editor):
    Product = apps.get_model("companies", "Product")
    Product.objects.filter(price_updated_at__isnull=True).filter(
        Q(price__isnull=False) | Q(min_price__isnull=False) | Q(max_price__isnull=False)
    ).update(price_updated_at=F("created"))


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0014_categoryaiprofile_recommendation_rules"),
        ("companies", "0009_local_parser_sync"),
        ("posts", "0031_backfill_post_attribute_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParserSourceAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("worker_name", models.CharField(blank=True, max_length=100)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(choices=[("success", "Success"), ("failure", "Failure")], max_length=20)),
                ("crawl_status", models.PositiveIntegerField(blank=True, null=True)),
                ("product_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Parser source attempt",
                "verbose_name_plural": "Parser source attempts",
                "ordering": ["-created"],
            },
        ),
        migrations.RunPython(backfill_product_price_updated_at, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_link__isnull", False), ("source_product_key__isnull", False)),
                fields=("source_link", "source_product_key"),
                name="companies_product_unique_source_product",
            ),
        ),
        migrations.AddField(
            model_name="parsersourceattempt",
            name="source_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="parser_attempts", to="companies.link"
            ),
        ),
    ]
