# Generated by Django 6.0 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_company_latitude_company_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="consecutive_missing_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="parsersourceattempt",
            name="parser_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsersourceattempt",
            name="parser_config_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="parsersourceattempt",
            name="snapshot_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productpricehistory",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="productpricehistory",
            index=models.Index(fields=["product", "-observed_at"], name="companies_price_product_obs"),
        ),
        migrations.AddIndex(
            model_name="productpricehistory",
            index=models.Index(fields=["source_link", "-observed_at"], name="companies_price_source_obs"),
        ),
    ]
