# Generated by Django 6.0.6 on 2026-09-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_alter_link_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="match_reason",
            field=models.CharField(blank=True, default="Попередній запис: зіставлення не перевірене.", max_length=1000),
        ),
        migrations.AddField(
            model_name="product",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("review", "Потребує перевірки"),
                    ("auto", "Повний збіг назви"),
                    ("confirmed", "Підтверджено адміністратором"),
                ],
                db_index=True,
                default="review",
                max_length=16,
            ),
        ),
    ]
