# Generated by Django 6.0.6 on 2026-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_product_match_reason_product_match_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMatchRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "word",
                    models.CharField(
                        help_text="Одне слово, без пробілів і пунктуації. Регістр не має значення.",
                        max_length=100,
                        unique=True,
                        verbose_name="Слово",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ignore", "Ігнорувати при зіставленні"),
                            ("bundle", "Маркер комплекту / кількох сортів"),
                        ],
                        default="ignore",
                        max_length=16,
                        verbose_name="Призначення",
                    ),
                ),
                (
                    "prefix",
                    models.BooleanField(
                        default=False,
                        help_text="Лише для маркерів комплектів: охоплює закінчення слова.",
                        verbose_name="Збіг за початком слова",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активне")),
            ],
            options={
                "verbose_name": "Правило зіставлення товарів",
                "verbose_name_plural": "Словник зіставлення товарів",
                "ordering": ("purpose", "word"),
            },
        ),
    ]
