# Generated by Django 6.0.6 on 2026-09-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0014_categoryaiprofile_recommendation_rules"),
        ("companies", "0016_seed_product_match_rules"),
        ("posts", "0033_merge_20260807_0000"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMatchAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Альтернативна назва")),
                ("active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Альтернативна назва сорту",
                "verbose_name_plural": "Альтернативні назви сортів",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="productmatchrule",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Порожньо — для всіх категорій. Вибрана категорія — без підкатегорій.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classifier.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="productmatchrule",
            name="word",
            field=models.CharField(
                help_text="Одне слово, без пробілів і пунктуації. Регістр не має значення.",
                max_length=100,
                verbose_name="Слово",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmatchrule",
            constraint=models.UniqueConstraint(
                fields=("word", "category"),
                condition=models.Q(category__isnull=False),
                name="unique_match_rule_word_category",
            ),
        ),
        migrations.AddField(
            model_name="productmatchalias",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_match_aliases",
                to="posts.post",
                verbose_name="Сорт каталогу",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmatchalias",
            constraint=models.UniqueConstraint(fields=("name", "post"), name="unique_product_match_alias"),
        ),
        migrations.AddConstraint(
            model_name="productmatchrule",
            constraint=models.UniqueConstraint(
                fields=("word",), condition=models.Q(category__isnull=True), name="unique_global_match_rule_word"
            ),
        ),
    ]
