# Generated by Django 6.0.6 on 2026-09-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0014_categoryaiprofile_recommendation_rules"),
        ("companies", "0017_productmatchalias_productmatchrule_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, max_length=200, verbose_name="Назва в навігації")),
                ("title", models.CharField(blank=True, max_length=250, verbose_name="SEO title")),
                ("description", models.CharField(blank=True, max_length=500, verbose_name="Meta description")),
                ("heading", models.CharField(blank=True, max_length=250, verbose_name="H1")),
                (
                    "text",
                    models.TextField(blank=True, help_text="Звичайний текст без HTML.", verbose_name="Текст сторінки"),
                ),
                (
                    "category",
                    models.OneToOneField(
                        blank=True,
                        help_text="Порожньо — головна сторінка Агромаркету.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classifier.category",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO-сторінка Агромаркету",
                "verbose_name_plural": "SEO-сторінки Агромаркету",
                "constraints": [
                    models.UniqueConstraint(
                        models.Value(1), condition=models.Q(("category__isnull", True)), name="single_market_root_page"
                    )
                ],
            },
        ),
    ]
